# Generated by Django 4.2.5 on 2023-10-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="name_en",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="name_uk",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="value_en",
            field=models.CharField(max_length=312, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="value_uk",
            field=models.CharField(max_length=312, null=True),
        ),
    ]
