# Generated by Django 4.2.5 on 2023-11-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact_name_en_contact_name_uk_contact_value_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="name_uk",
        ),
    ]
