# Generated by Django 4.2.5 on 2023-11-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_remove_contact_name_en_remove_contact_name_uk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "contact", "verbose_name_plural": "contacts"},
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=64, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="value",
            field=models.CharField(max_length=312, verbose_name="value"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="value_en",
            field=models.CharField(max_length=312, null=True, verbose_name="value"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="value_uk",
            field=models.CharField(max_length=312, null=True, verbose_name="value"),
        ),
    ]
