# Generated by Django 4.2.5 on 2023-11-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_contact_options_alter_contact_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.SlugField(max_length=64, verbose_name="name"),
        ),
    ]
