# Generated by Django 4.2.5 on 2023-10-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("logo", models.ImageField(upload_to="logo")),
                (
                    "logo_dark_theme",
                    models.ImageField(
                        default="img.freepik.com/free-vector/bird-colorful-logo-gradient-vector_343694-1365.jpg",
                        upload_to="logo-dark-theme",
                    ),
                ),
                ("website", models.URLField(unique=True)),
            ],
        ),
    ]
