# Generated by Django 4.2.5 on 2023-10-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("classic_logo", models.ImageField(upload_to="logo/classic")),
                ("dark_logo", models.ImageField(upload_to="logo/dark")),
                ("website", models.URLField(unique=True)),
            ],
        ),
    ]
