# Generated by Django 4.2.5 on 2023-10-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=models.ImageField(upload_to="logo"),
        ),
    ]
