# Generated by Django 4.2.5 on 2023-11-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partner",
            options={"verbose_name": "partner", "verbose_name_plural": "partners"},
        ),
        migrations.AlterField(
            model_name="partner",
            name="classic_logo",
            field=models.ImageField(
                upload_to="logo/classic", verbose_name="classic logo"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="dark_logo",
            field=models.ImageField(upload_to="logo/dark", verbose_name="dark logo"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="name",
            field=models.CharField(max_length=64, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="website",
            field=models.URLField(unique=True, verbose_name="website"),
        ),
    ]
