# Generated by Django 4.2.5 on 2023-10-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_alter_partner_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="logo_dark_theme",
            field=models.ImageField(
                default="img.freepik.com/free-vector/bird-colorful-logo-gradient-vector_343694-1365.jpg",
                upload_to="logo-dark-theme",
            ),
        ),
    ]
