# Generated by Django 4.2.5 on 2023-11-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_alter_partner_options_alter_partner_classic_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="name_en",
            field=models.CharField(
                max_length=64, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="name_uk",
            field=models.CharField(
                max_length=64, null=True, unique=True, verbose_name="name"
            ),
        ),
    ]
