# Generated by Django 4.2.5 on 2023-11-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "document", "verbose_name_plural": "documents"},
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="documents", verbose_name="file"),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(max_length=48, verbose_name="name"),
        ),
    ]
