# Generated by Django 4.2.5 on 2023-11-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_document_options_alter_document_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.SlugField(max_length=64, verbose_name="name"),
        ),
    ]
