# Generated by Django 4.2.5 on 2023-10-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lullaby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("AK", "Autonomous Republic of Crimea"),
                            ("AB", "Vinnytsia Oblast"),
                            ("AC", "Volyn Oblast"),
                            ("AR", "Dnipropetrovsk Oblast"),
                            ("AH", "Donetsk Oblast"),
                            ("AM", "Zhytomyr Oblast"),
                            ("AO", "Zakarpattia Oblast"),
                            ("AP", "Zaporizhzhia Oblast"),
                            ("AT", "Ivano-Frankivsk Oblast"),
                            ("AA", "Kyiv Oblast"),
                            ("BA", "Kirovohrad Oblast"),
                            ("BB", "Luhansk Oblast"),
                            ("BC", "Lviv Oblast"),
                            ("BE", "Mykolaiv Oblast"),
                            ("BH", "Odesa Oblast"),
                            ("BI", "Poltava Oblast"),
                            ("BK", "Rivne Oblast"),
                            ("BM", "Sumy Oblast"),
                            ("BO", "Ternopil Oblast"),
                            ("AX", "Kharkiv Oblast"),
                            ("BT", "Kherson Oblast"),
                            ("BX", "Khmelnytskyi Oblast"),
                            ("CA", "Cherkasy Oblast"),
                            ("CE", "Chernivtsi Oblast"),
                            ("CB", "Chernihiv Oblast"),
                        ],
                        max_length=64,
                    ),
                ),
                ("lyrics", models.TextField()),
            ],
            options={
                "verbose_name_plural": "lullabies",
            },
        ),
        migrations.CreateModel(
            name="MediaSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.URLField(blank=True, null=True)),
                ("audio", models.FileField(blank=True, default="", upload_to="audio/")),
                (
                    "cover",
                    models.ImageField(blank=True, default="", upload_to="cover/"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="mediasource",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("video__isnull", True), ("audio__exact", ""), _connector="XOR"
                ),
                name="only_one_source_is_set",
                violation_error_message="You need to specify only one source of media: video or audio.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediasource",
            constraint=models.CheckConstraint(
                check=models.ExpressionWrapper(
                    models.Case(
                        models.When(
                            models.Q(("audio__exact", ""), _negated=True),
                            then=models.Q(("cover__exact", ""), _negated=True),
                        ),
                        default=models.Value(True),
                    ),
                    output_field=models.BooleanField(),
                ),
                name="audio_has_cover",
                violation_error_message="If you use audio as a source, you need to upload a cover.",
            ),
        ),
        migrations.AddField(
            model_name="lullaby",
            name="artists",
            field=models.ManyToManyField(
                blank=True, related_name="lullabies", to="artists.artist"
            ),
        ),
        migrations.AddField(
            model_name="lullaby",
            name="source",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="lullabies",
                to="lullabies_app.mediasource",
            ),
        ),
    ]
