# Generated by Django 4.2.5 on 2023-09-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lullabies_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lullaby",
            options={"verbose_name_plural": "lullabies"},
        ),
    ]
