# Generated by Django 4.2.5 on 2023-10-04 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lullabies_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lullaby",
            name="source",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="lullaby",
                to="lullabies_app.mediasource",
            ),
        ),
    ]
