# Generated by Django 4.2.5 on 2023-10-05 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("lullabies_app", "0002_alter_lullaby_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lullaby",
            name="source",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="lullaby",
                to="media.mediasource",
            ),
        ),
        migrations.DeleteModel(
            name="MediaSource",
        ),
    ]
