# Generated by Django 4.2.5 on 2023-10-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lullabies_app", "0003_alter_lullaby_source_delete_mediasource"),
    ]

    operations = [
        migrations.AddField(
            model_name="lullaby",
            name="views",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
