# Generated by Django 4.2.5 on 2023-09-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lullabies_app", "0003_lullaby_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lullaby",
            name="region",
            field=models.IntegerField(
                choices=[
                    (1, "Autonomous Republic of Crimea"),
                    (2, "Vinnytsia Oblast"),
                    (3, "Volyn Oblast"),
                    (4, "Dnipropetrovsk Oblast"),
                    (5, "Donetsk Oblast"),
                    (6, "Zhytomyr Oblast"),
                    (7, "Zakarpattia Oblast"),
                    (8, "Zaporizhzhia Oblast"),
                    (9, "Ivano-Frankivsk Oblast"),
                    (10, "Kyiv Oblast"),
                    (11, "Kirovohrad Oblast"),
                    (12, "Luhansk Oblast"),
                    (13, "Lviv Oblast"),
                    (14, "Mykolaiv Oblast"),
                    (15, "Odesa Oblast"),
                    (16, "Poltava Oblast"),
                    (17, "Rivne Oblast"),
                    (18, "Sumy Oblast"),
                    (19, "Ternopil Oblast"),
                    (20, "Kharkiv Oblast"),
                    (21, "Kherson Oblast"),
                    (22, "Khmelnytskyi Oblast"),
                    (23, "Cherkasy Oblast"),
                    (24, "Chernivtsi Oblast"),
                    (25, "Chernihiv Oblast"),
                ],
            ),
        ),
    ]
