# Generated by Django 4.2.5 on 2023-10-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lullabies_app", "0004_lullaby_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lullaby",
            name="lyrics",
            field=models.TextField(blank=True, default=""),
        ),
    ]
