# Generated by Django 4.2.5 on 2023-09-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0001_initial"),
        ("lullabies_app", "0005_alter_lullaby_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="lullaby",
            name="artists",
            field=models.ManyToManyField(
                blank=True, related_name="lullabies", to="artists.artist"
            ),
        ),
    ]
