# Generated by Django 4.2.5 on 2023-10-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lullabies_app", "0005_alter_lullaby_lyrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="lullaby",
            name="lyrics_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="lullaby",
            name="lyrics_uk",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="lullaby",
            name="name_en",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="lullaby",
            name="name_uk",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
