# Generated by Django 4.2.5 on 2023-10-02 07:03

from django.db import migrations, models
import django.db.models.deletion


def create_default_source(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Source = apps.get_model("lullabies_app", "MediaSource")
    Source.objects.using(db_alias).create(
        video="https://www.youtube.com/watch?v=IVNCmQFjCZQ"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("lullabies_app", "0006_lullaby_artists"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.URLField(blank=True, null=True)),
                ("audio", models.FileField(blank=True, default="", upload_to="")),
                ("cover", models.FileField(blank=True, default="", upload_to="")),
            ],
        ),
        migrations.RemoveField(
            model_name="lullaby",
            name="url",
        ),
        migrations.AddConstraint(
            model_name="mediasource",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("video__isnull", False),
                    models.Q(("audio__exact", ""), _negated=True),
                    _connector="XOR",
                ),
                name="only_one_source_is_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediasource",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("video__isnull", False),
                    models.Q(("audio__exact", ""), ("cover__exact", "")),
                    _connector="OR",
                ),
                name="audio_has_cover",
            ),
        ),
        migrations.RunPython(create_default_source),
        migrations.AddField(
            model_name="lullaby",
            name="source",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="lullabies",
                to="lullabies_app.mediasource",
            ),
        ),
    ]
