# Generated by Django 4.2.5 on 2023-10-12 08:44

from django.db import migrations


def fill_region_fk(apps, schema_editor):
    Lullaby = apps.get_model("lullabies_app", "Lullaby")
    Region = apps.get_model("lullabies_app", "Region")
    for obj in Lullaby.objects.all():
        obj.region_fk, created = Region.objects.get_or_create(
            name=obj.get_region_display()
        )
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("lullabies_app", "0007_region_lullaby_region_fk"),
    ]

    operations = [
        migrations.RunPython(fill_region_fk, migrations.RunPython.noop),
    ]
