# Generated by Django 4.2.5 on 2023-10-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lullabies_app", "0007_mediasource_remove_lullaby_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lullaby",
            name="source",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="lullabies",
                to="lullabies_app.mediasource",
            ),
        ),
    ]
