# Generated by Django 4.2.5 on 2023-10-12 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lullabies_app", "0008_auto_20231012_1144"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lullaby",
            name="region",
        ),
        migrations.RenameField(
            model_name="lullaby",
            old_name="region_fk",
            new_name="region",
        ),
    ]
