# Generated by Django 4.2.5 on 2023-10-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lullabies_app", "0008_alter_lullaby_source"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mediasource",
            name="only_one_source_is_set",
        ),
        migrations.RemoveConstraint(
            model_name="mediasource",
            name="audio_has_cover",
        ),
        migrations.AlterField(
            model_name="mediasource",
            name="audio",
            field=models.FileField(blank=True, default="", upload_to="audio/"),
        ),
        migrations.AlterField(
            model_name="mediasource",
            name="cover",
            field=models.FileField(blank=True, default="", upload_to="cover/"),
        ),
        migrations.AddConstraint(
            model_name="mediasource",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("video__isnull", True), ("audio__exact", ""), _connector="XOR"
                ),
                name="only_one_source_is_set",
                violation_error_message="You need to specify only one source of media: video or audio.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediasource",
            constraint=models.CheckConstraint(
                check=models.ExpressionWrapper(
                    models.When(
                        models.Q(("audio__exact", ""), _negated=True),
                        then=models.Q(("cover__exact", ""), _negated=True),
                    ),
                    output_field=models.BooleanField(),
                ),
                name="audio_has_cover",
                violation_error_message="If you use audio as a source, you need to upload a cover.",
            ),
        ),
    ]
