# Generated by Django 4.2.5 on 2023-10-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lullabies_app", "0009_remove_mediasource_only_one_source_is_set_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mediasource",
            name="audio_has_cover",
        ),
        migrations.AlterField(
            model_name="mediasource",
            name="cover",
            field=models.ImageField(blank=True, default="", upload_to="cover/"),
        ),
        migrations.AddConstraint(
            model_name="mediasource",
            constraint=models.CheckConstraint(
                check=models.ExpressionWrapper(
                    models.Case(
                        models.When(
                            models.Q(("audio__exact", ""), _negated=True),
                            then=models.Q(("cover__exact", ""), _negated=True),
                        ),
                        default=models.Value(True),
                    ),
                    output_field=models.BooleanField(),
                ),
                name="audio_has_cover",
                violation_error_message="If you use audio as a source, you need to upload a cover.",
            ),
        ),
    ]
