# Generated by Django 4.2.5 on 2023-10-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lullabies_app", "0009_remove_lullaby_region_fk_alter_lullaby_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="name_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="name_uk",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="lullabies",
                to="lullabies_app.region",
            ),
        ),
    ]
