# Generated by Django 4.2.5 on 2023-10-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lullabies_app", "0010_region_name_en_region_name_uk_alter_lullaby_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lullaby",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="lullabies",
                to="lullabies_app.region",
            ),
        ),
    ]
