# Generated by Django 4.2.5 on 2023-10-21 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0002_artist_name_en_artist_name_uk"),
        ("lullabies_app", "0011_alter_lullaby_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lullaby",
            name="artists",
        ),
        migrations.AddField(
            model_name="lullaby",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lullabies",
                to="artists.artist",
            ),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lullabies",
                to="lullabies_app.region",
            ),
        ),
        migrations.AddConstraint(
            model_name="lullaby",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("region__isnull", True), ("artist__isnull", True), _connector="XOR"
                ),
                name="only_region_or_artist_is_set",
                violation_error_message="You need to specify only region or artist.",
            ),
        ),
    ]
