# Generated by Django 4.2.5 on 2023-11-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lullabies_app", "0012_remove_lullaby_artists_lullaby_artist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lullaby",
            name="type",
            field=models.CharField(
                choices=[("new", "new"), ("archive", "archive")], default="archive"
            ),
        ),
    ]
