# Generated by Django 4.2.5 on 2023-11-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lullabies_app", "0013_lullaby_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lullaby",
            name="only_region_or_artist_is_set",
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="type",
            field=models.CharField(choices=[("new", "new"), ("archive", "archive")]),
        ),
    ]
