# Generated by Django 4.2.5 on 2023-11-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lullabies_app", "0014_remove_lullaby_only_region_or_artist_is_set_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="slug",
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
    ]
