# Generated by Django 4.2.5 on 2023-11-19 23:59

from django.db import migrations
from django.utils.text import slugify


def slugify_regions(apps, schema_editor):
    for region in apps.get_model("lullabies_app", "region").objects.all():
        region.slug = slugify(region.name)
        region.save()


class Migration(migrations.Migration):
    dependencies = [
        ("lullabies_app", "0015_region_slug"),
    ]

    operations = [
        migrations.RunPython(slugify_regions, migrations.RunPython.noop),
    ]
