# Generated by Django 4.2.5 on 2023-11-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lullabies_app", "0016_auto_20231120_0159"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="slug",
            field=models.SlugField(blank=True, max_length=128, unique=True),
        ),
    ]
