# Generated by Django 4.2.5 on 2023-11-21 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0004_alter_mediasource_options_alter_mediasource_audio_and_more"),
        ("artists", "0004_alter_artist_options_alter_artist_name_and_more"),
        ("lullabies_app", "0017_alter_region_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lullaby",
            options={"verbose_name": "lullaby", "verbose_name_plural": "lullabies"},
        ),
        migrations.AlterModelOptions(
            name="region",
            options={"verbose_name": "region", "verbose_name_plural": "regions"},
        ),
        migrations.AddField(
            model_name="lullaby",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="is visible"),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lullabies",
                to="artists.artist",
                verbose_name="artist",
            ),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="lyrics",
            field=models.TextField(blank=True, default="", verbose_name="lyrics"),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="lyrics_en",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="lyrics"
            ),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="lyrics_uk",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="lyrics"
            ),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="name",
            field=models.CharField(max_length=64, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="name_en",
            field=models.CharField(max_length=64, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="name_uk",
            field=models.CharField(max_length=64, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lullabies",
                to="lullabies_app.region",
                verbose_name="region",
            ),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="source",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="lullaby",
                to="media.mediasource",
                verbose_name="source",
            ),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="type",
            field=models.CharField(
                choices=[("new", "new"), ("archive", "archive")], verbose_name="type"
            ),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="views",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="views"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=128, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="region",
            name="name_en",
            field=models.CharField(max_length=128, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="region",
            name="name_uk",
            field=models.CharField(max_length=128, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="region",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=128, unique=True, verbose_name="slug"
            ),
        ),
    ]
