# Generated by Django 4.2.5 on 2023-11-28 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lullabies_app", "0018_alter_lullaby_options_alter_region_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lullaby",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 28, 10, 40, 11, 109855, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
        migrations.AddField(
            model_name="lullaby",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
