# Generated by Django 4.2.5 on 2023-11-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lullabies_app", "0019_lullaby_created_lullaby_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lullaby",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
