# Generated by Django 4.2.5 on 2024-12-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lullabies_app', '0020_alter_lullaby_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lullaby',
            name='type',
            field=models.CharField(choices=[('new', 'new'), ('archive', 'archive')], max_length=16, verbose_name='type'),
        ),
    ]
