# Generated by Django 4.2.5 on 2024-12-05 11:35

from django.db import migrations, models
import lullabies_app.models.boost


class Migration(migrations.Migration):

    dependencies = [
        ('lullabies_app', '0021_alter_lullaby_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=lullabies_app.models.boost.today_date, unique=True)),
                ('lullabies', models.ManyToManyField(related_name='boosts', to='lullabies_app.lullaby', verbose_name='lullabies')),
            ],
            options={
                'verbose_name': 'boost',
                'verbose_name_plural': 'boosts',
            },
        ),
    ]
