# Generated by Django 4.2.5 on 2023-10-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="name_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="name_uk",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
