# Generated by Django 4.2.5 on 2023-11-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0002_artist_name_en_artist_name_uk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="name_uk",
        ),
    ]
