# Generated by Django 4.2.5 on 2023-11-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0003_remove_artist_name_en_remove_artist_name_uk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={"verbose_name": "artist", "verbose_name_plural": "artists"},
        ),
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(max_length=128, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="artist",
            name="sex",
            field=models.CharField(
                choices=[("M", "male"), ("F", "female"), ("U", "undefined")],
                max_length=16,
                verbose_name="sex",
            ),
        ),
    ]
