# Generated by Django 4.2.5 on 2023-10-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.URLField(blank=True, null=True)),
                ("audio", models.FileField(blank=True, default="", upload_to="audio/")),
                (
                    "cover",
                    models.ImageField(blank=True, default="", upload_to="cover/"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="mediasource",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("video__isnull", True), ("audio__exact", ""), _connector="XOR"
                ),
                name="only_one_source_is_set",
                violation_error_message="You need to specify only one source of media: video or audio.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediasource",
            constraint=models.CheckConstraint(
                check=models.ExpressionWrapper(
                    models.Case(
                        models.When(
                            models.Q(("audio__exact", ""), _negated=True),
                            then=models.Q(("cover__exact", ""), _negated=True),
                        ),
                        default=models.Value(True),
                    ),
                    output_field=models.BooleanField(),
                ),
                name="audio_has_cover",
                violation_error_message="If you use audio as a source, you need to upload a cover.",
            ),
        ),
    ]
