# Generated by Django 4.2.5 on 2023-10-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediasource",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
