# Generated by Django 4.2.5 on 2023-11-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_mediasource_duration"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mediasource",
            name="audio_has_cover",
        ),
        migrations.RemoveField(
            model_name="mediasource",
            name="cover",
        ),
        migrations.AddField(
            model_name="mediasource",
            name="preview",
            field=models.ImageField(blank=True, default="", upload_to="preview/"),
        ),
        migrations.AddConstraint(
            model_name="mediasource",
            constraint=models.CheckConstraint(
                check=models.ExpressionWrapper(
                    models.Case(
                        models.When(
                            models.Q(("video__isnull", False)),
                            then=models.Q(("preview__exact", ""), _negated=True),
                        ),
                        default=models.Value(True),
                    ),
                    output_field=models.BooleanField(),
                ),
                name="video_has_preview",
                violation_error_message="If you use video as a source, you need to upload a preview.",
            ),
        ),
    ]
