# Generated by Django 4.2.5 on 2023-11-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_remove_mediasource_audio_has_cover_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediasource",
            options={"verbose_name": "media", "verbose_name_plural": "media"},
        ),
        migrations.AlterField(
            model_name="mediasource",
            name="audio",
            field=models.FileField(
                blank=True, default="", upload_to="audio/", verbose_name="audio"
            ),
        ),
        migrations.AlterField(
            model_name="mediasource",
            name="duration",
            field=models.DurationField(blank=True, null=True, verbose_name="duration"),
        ),
        migrations.AlterField(
            model_name="mediasource",
            name="preview",
            field=models.ImageField(
                blank=True, default="", upload_to="preview/", verbose_name="preview"
            ),
        ),
        migrations.AlterField(
            model_name="mediasource",
            name="video",
            field=models.URLField(blank=True, null=True, verbose_name="video"),
        ),
    ]
