# Generated by Django 4.2.5 on 2023-11-28 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0004_alter_mediasource_options_alter_mediasource_audio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediasource",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 28, 10, 35, 45, 878620, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
        migrations.AddField(
            model_name="mediasource",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
