# Generated by Django 4.2.5 on 2023-11-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0005_mediasource_created_mediasource_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediasource",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
